### ISSUE TITLE
Inappropriate path in generate.py

### ISSUE THREAD

**Issue by takenori-y** [SALT-NLP/demonstrated-feedback#3]
This is a trivial report:
https://github.com/SALT-NLP/demonstrated-feedback/blob/1a7c8dca64bcf52efa94bb94629db85885799aad/generate.py#L49
should be
```py
 path = f"./benchmarks/{args.benchmark}/processed/{args.benchmark}_test.pkl"
```

**Comment by oshaikh13** [comment]
good catch, fixed!
